import getAllCategory from '@/Api/AllCategory';
import CategoryTpe from '@/Types/Category.Type';
import Image from 'next/image';
import React from 'react'
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Page Category ❤️",
  description: "Generated by create next app",
};
export default async function Categories() {
  const data = await getAllCategory();
  console.log(data)
  return (
    <div className="gap-2 my-12 w-2/3 mx-auto grid grid-cols-2 lg:grid-cols-4 sm:grid-cols-3 ">
      {data.map((product : CategoryTpe)=>(
        <div key={product._id}>
          <div>
          <div className='w-[80%] justify-center border-4 rounded-3xl'>
        <Image width={500} height={500} src={product.image} alt={product.name} className='rounded-3xl p-2'/>
        <div className=' p-3 text-center text-2xl'>
             {product.name}
           </div>
        </div>
           </div>
           </div>
      ))}
     
    </div>
  )
}
