import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import Navbar from "./_componente/navbar/page";
import Footer from "./_componente/footer/page";
import MySessionProvider from "@/MysessionProvider/MySessionProvider";
import  CartContextProvider  from '@/context/CartContext';
import WishlistContextProvider from "@/context/WishlistContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
       <MySessionProvider>
        <CartContextProvider>
        <WishlistContextProvider>
         <Navbar/>
        {children}
         <Toaster />
        
        </WishlistContextProvider>
        </CartContextProvider>
       </MySessionProvider>
         <div className="bg-gray-800 text-white text-center p-4 mt-[20%] ">
        <Footer/>
      </div>
      </body>
    </html>
  );
}
