import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import Navbar from "./_componente/navbar/page";
import Footer from "./_componente/footer/page";
import MySessionProvider from "@/MysessionProvider/MySessionProvider";
import  CartContextProvider  from '@/context/CartContext';
import WishlistContextProvider from "@/context/WishlistContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
        <div className="min-h-screen flex flex-col">
          <MySessionProvider>
            <CartContextProvider>
              <WishlistContextProvider>
                <Navbar />
                <main className="flex-1">{children}</main>
                <Toaster />
                <Footer />
              </WishlistContextProvider>
            </CartContextProvider>
          </MySessionProvider>
        </div>
      </body>
    </html>
  );
}
