import LimtBrands from "@/Api/Brands";
import Category from "./_componente/CategorySwiper/Category";
import MainSlider from "./_componente/MainSlider/MainSlider";
import type { Metadata } from "next";
import LimtProducts from "@/Api/LimtProducts";
export const metadata: Metadata = {
  title: "Home ❤️",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <div className="mx-auto w-[80%] my-10">
      <MainSlider/>
      <Category/>
      <LimtBrands/>
      <LimtProducts/>
    </div>
  )
}
