import LimtBrands from "@/Api/Brands";
import Category from "./_componente/CategorySwiper/Category";
import MainSlider from "./_componente/MainSlider/MainSlider";
import type { Metadata } from "next";
import LimtProducts from "@/Api/LimtProducts";
export const metadata: Metadata = {
  title: "Home ❤️",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <div className="w-full px-3 sm:px-4">
      <div className="mx-auto w-full max-w-7xl py-6 sm:py-8 md:py-10 space-y-8 sm:space-y-10">
        <MainSlider />
        <Category />
        <LimtBrands />
        <LimtProducts />
      </div>
    </div>
  )
}
