import { IoStarSharp } from "react-icons/io5";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
} from "@/components/ui/card";
import Link from "next/link";
import { ProductType } from "@/Types/Product.Type";
import Image from "next/image";
import ButtonAddToCart from "@/FileClientComponent/ButtonAddToCart";
import ButtonAddToWishlist from "@/FileClientComponent/ButtonAddHeart";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Page Products ❤️",
  description: "Generated by create next app",
};
export default async function Products() {
  const response = await fetch(
    "https://ecommerce.routemisr.com/api/v1/products",
    {
      cache: "no-store",
    }
  );
  const { data } = await response.json();
  console.log(data);
  return(
    <>
    {/* get all Products page ==> Products */}
    <div className="w-full">
      <h1 className="text-center text-2xl sm:text-3xl md:text-4xl text-blue-900 py-4 sm:py-6 px-4">
        Products page
      </h1>
      <div className="w-full sm:w-[95%] md:w-[90%] mx-auto px-3 sm:px-4 pb-8">
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 sm:gap-4 md:gap-6">
          {data.map((product: ProductType) => (
            <div key={product.id} className="flex flex-col">
              <Card className="p-3 sm:p-4 gap-3 flex flex-col h-full">
                <div className='hover:text-red-500 transition text-lg'>
                  <ButtonAddToWishlist id={product.id}/>
                </div>
                <Link href={`/productDetails/${product.id}`} className="flex-1">
                  <CardHeader className="p-0 mb-2">
                    <Image
                      className='w-full h-40 sm:h-44 md:h-48 object-contain rounded-lg'
                      width={500}
                      height={500}
                      src={product.imageCover}
                      alt="Product image"
                    />
                  </CardHeader>
                  <CardContent className="flex flex-col sm:flex-row gap-2 justify-between p-0 mb-2 text-xs sm:text-sm">
                    <p className="font-bold text-blue-800 truncate">
                      {product.category.name}
                    </p>
                    <p className="font-bold text-red-500 truncate">
                      {product.brand.name}
                    </p>
                  </CardContent>
                  <p className="text-xs sm:text-sm font-semibold text-gray-800 line-clamp-2 mb-2">
                    {product.title}
                  </p>
                  <CardFooter className="flex flex-col sm:flex-row gap-2 justify-between p-0 items-start sm:items-center">
                    <button className="bg-red-600 text-white text-xs sm:text-sm px-2 sm:px-3 py-1 rounded-full whitespace-nowrap">
                      {product.price} EGP
                    </button>
                    <p className="flex items-center gap-1 text-yellow-500 text-xs sm:text-sm">
                      <span>{product.ratingsAverage}</span>
                      <i className="text-yellow-300">
                        <IoStarSharp />
                      </i>
                    </p>
                  </CardFooter>
                </Link>
              </Card>
              <div className="mt-2">
                <ButtonAddToCart id={product.id} />
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
    </>
  )
}
