import { IoStarSharp } from "react-icons/io5";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
} from "@/components/ui/card";
import Link from "next/link";
import { ProductType } from "@/Types/Product.Type";
import Image from "next/image";
import ButtonAddToCart from "@/FileClientComponent/ButtonAddToCart";
import ButtonAddToWishlist from "@/FileClientComponent/ButtonAddHeart";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Page Products ❤️",
  description: "Generated by create next app",
};
export default async function Products() {
  const response = await fetch(
    "https://ecommerce.routemisr.com/api/v1/products",
    {
      cache: "no-store",
    }
  );
  const { data } = await response.json();
  console.log(data);
  return(
    <>
    {/* get all Products page ==> Products */}
    <div>
      <h1 className="text-center text-4xl text-blue-900 gap-4 p-4">
        Products page
      </h1>
      <div className="w-[80%] mx-auto  grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 ">
        {data.map((product: ProductType) => (
          <div key={product.id}>
              <Card className="p-4 gap-3">
              <div className='hover:text-red-500'><ButtonAddToWishlist id={product.id}/></div>
            <Link href={`/productDetails/${product.id}`}>
                <CardHeader>
                  <Image
                  className='w-full h-48 object-contain rounded-t-lg'
                    width={500}
                    height={500}
                    src={product.imageCover}
                    alt=".... image Product"
                  />
                </CardHeader>
                <CardContent className="flex justify-between">
                  <p className="font-bold text-blue-800 mb-3">
                    {product.category.name}
                  </p>
                  <p className="font-bold text-red-500 mb-3 ">
                    {product.brand.name}
                  </p>
                </CardContent>
                <p className="text-sm font-semibold text-gray-800 line-clamp-1">
                  {product.title}
                </p>
                <CardFooter className="flex justify-between">
                  <div className="flex justify-around py-4 px-2 mb-3">
                    <button className="bg-red-600 text-white text-sm px-2 py-1 rounded-2xl">
                      {product.price} EGP
                    </button>
                    </div>
                    <p className="flex items-center text-yellow-500 text-sm">
                      {product.ratingsAverage}
                      <i className="text-yellow-300 ">
                        <IoStarSharp />
                      </i>
                    </p>
                </CardFooter>
                </Link>
              </Card>
            <ButtonAddToCart id={product.id} />
          </div>
        ))}
      </div>
    </div>
    </>
  )
}
