import Image from 'next/image';
import React from 'react'
import { Daum } from '@/Types/Brand.Type';
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Page Brands ❤️",
  description: "Generated by create next app",
};
export default async function Brands() {
     
  const res = await fetch(`https://ecommerce.routemisr.com/api/v1/brands`, {
     cache: "no-store",
    method: "GET",
  })
    const { data } = await res.json();
  console.log(data);
  
  return (
      <div className="gap-2 w-[80%] mx-auto grid grid-cols-2 lg:grid-cols-4 sm:grid-cols-3  shadow-3xl">
        {data.map((product :Daum) => (
          <div key={product._id}>
              <div className="p-4 gap-3 ">
                  <Image
                    width={500}
                    height={500}
                    src={product.image}
                    alt={product.name}
                  />
                  <div className='flex justify-center p-2 bg-black text-white '>
                  {product.name}
                  </div>
              </div>
          </div>
        ))}
      </div>
          
  )
}
