import { IoStarSharp } from "react-icons/io5";
import Link from 'next/link';
import Buttonproductimage from '../../../FileClientComponent/Button.productimage';
import ButtonAddToCart from "@/FileClientComponent/ButtonAddToCart";
import Image from "next/image";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "ProductsDetails ❤️",
  description: "Generated by create next app",
};
export default async function  ProductDetails({params } : {params :Promise< {id: string}>} ) {
  const {id} = await params;
  //{================Api ProductDetails============}
  const response = await fetch(`https://ecommerce.routemisr.com/api/v1/products/${id}`)
   const data = await response.json()
  //  console.log(data)
  //  if(!data) return <h1>No Products Here !!</h1>
  //  const RelatedProducts = await getRelated(CategoryTpe._id)
  //  console.log(RelatedProducts)
   // data.category._id ===> category id ===> current product
  return (
    <div className='conatiner mx-auto px-4 py-8 w-[80%]'> 
    <div className='grid grid-cols-1 lg:grid-cols-2 gap-8'>
       <div className='space-y-4 w-[80%]'>
        <div className=' relative aspect-square overflow-hidden rounded-lg border'>
       <Image width={500} height={500} src={data.data.imageCover}alt='image the product' className='object-contain ' />
        </div>
    {/*========== Thumbnail Image ==========*/}
          <Buttonproductimage images={data.data.images} title={data.data.title} />
       </div>
    {/*========== product Info ==========*/}
    <div className='space-y-6'>
      {/*========== Brand ==========*/}
      <div className='text-sm text-muted-foreground uppercase tracking-wide'>
        <Link href='' className='hover:text-primary hover:underline transition-colors'>
        {data.data.brand.name}
        </Link>
      </div>
      {/*========== Title ==========*/}
      <h1 className='text-3xl font-bold'>{data.data.title}</h1>
      {/*========== Rating ==========*/}
      <div className='flex items-center gap-4'>
        <div className='flex items-center gap-1'>
          <span className='ml-2 text-sm text-muted-foreground flex gap-2'>
            <i className="text-yellow-300 my-1"><IoStarSharp /></i>
            <i className="text-yellow-300 my-1"><IoStarSharp /></i>
            <i className="text-yellow-300 my-1"><IoStarSharp /></i>
            <i className="text-yellow-300 my-1"><IoStarSharp /></i>
            <i className="text-yellow-300 my-1"><IoStarSharp /></i>
            {data.data.ratingsAverage}({data.data.ratingsQuantity} reviews)
          </span>
        </div>
        <span className='text-sm text-muted-foreground'>{data.data.sold}</span>
      </div>
      {/*========== price ==========*/}
      <div className='text-3xl font-bold text-primary'>
       ${data.data.price}
      </div>
   {/*========== Description========== */}
   <div className='space-y-2'>
    <h3 className='font-semibold'>Description</h3>
    <p className='text-muted-foreground leading-relaxed'>{data.data.description}</p>
   </div>
   {/* ========== Category ========== 
   {/* <div className='flex flex-wrap gap-2'>
   <Link href={``} className='px-3 py-1 bg-secondary text-secondary-foreground rounded-full text-sm hover:bg-secondary'>{data.data.category}</Link> 
   </div>  */}
   {/* Stock Status */}
   <div className='flex items-center gap-2'>
    <span className='text-sm font-medium'>Stock:</span>
    <span className={`text-sm ${data.data.quantity >0 ? "text-green-600" : " text-red-500"}`}>{data.data.quantity > 0 ? `${data.data.quantity} available` : "out of Stock"}</span>
   </div>
   {/*============== Action Buttons ==========*/}
   <div className='flex gap-4 '>
       <ButtonAddToCart id={id} />
    {/* <Button variant='outline' size='lg' className='h-10 w-10'>
      <CiHeart/>
    </Button> */}
   </div>
   {/* ========== features ========== */}
   <div className='grid grid-cols-1 mg:grid-cols-3 gap-3 pt-6 border-t'>
    <div className='flex items-center gap-3'>
      {/* <Truck className='h-5 w-5 text-primary'/> */}
      <div>
        <p className='font-medium text-sm'>free Shopping</p>
        <p className='text-muted-foreground text-xs'>on orders over $50</p>
      </div>

    </div>
   </div>
    </div>
    </div>
    </div>
  )
}